---
all:
  vars:
    ansible_user: vagrant
    ansible_ssh_private_key_file: .vagrant/machines/teleport-bastion/virtualbox/private_key
    ansible_become: yes
    ansible_become_method: sudo

  children:
    bastion:
      hosts:
        teleport-bastion:
          ansible_host: 192.168.56.10

    target:
      hosts:
        target-server:
          ansible_host: 192.168.56.11
