---
- name: Deploy Target Server (Nginx + MySQL + Teleport Agent)
  hosts: target-server
  become: yes
  gather_facts: yes
  vars:
    teleport_mode: agent
    teleport_nodename: target-server
    teleport_db_service_enabled: true

  pre_tasks:
    - name: Ensure bastion_ip is set from group_vars
      debug:
        msg: "Using bastion_ip from group_vars: {{ bastion_ip }}"

  roles:
    - nginx
    - mysql
    - teleport

